name: bmi_calculator

description: BMI Calculator with flutter

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.4.0
  flutter_bloc: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0


flutter:

  uses-material-design: true
